github:
  repoUrl: ""
  chartPath: "charts/django-app"
  targetRevision: "main"

application:
  name: django-app
  namespace: default
  project: default

sync:
  automated: true
  selfHeal: true
  prune: true
