server:
  service:
    type: ${service_type}
  
  resources:
    requests:
      cpu: "100m"
      memory: "200Mi"
    limits:
      cpu: "300m"
      memory: "400Mi"
  
  extraArgs:
    - --insecure

configs:
  params:
    server.insecure: true
  
  cm:
    timeout.reconciliation: 30s
    application.instanceLabelKey: argocd.argoproj.io/instance

repoServer:
  resources:
    requests:
      cpu: "100m"
      memory: "200Mi"
    limits:
      cpu: "300m"
      memory: "400Mi"

controller:
  resources:
    requests:
      cpu: "150m"
      memory: "300Mi"
    limits:
      cpu: "300m"
      memory: "600Mi"

redis:
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "150m"
      memory: "128Mi"

applicationSet:
  enabled: false

notifications:
  enabled: false

dex:
  enabled: false
