apiVersion: v2
name: django-app
description: A Helm chart for Django microservice application
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - django
  - python
  - microservice
maintainers:
  - name: Budyakov Maxim
    email: budyakov@gmail.com
