apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.application.name }}
  namespace: {{ .Release.Namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.application.project }}
  
  source:
    repoURL: {{ .Values.github.repoUrl }}
    targetRevision: {{ .Values.github.targetRevision }}
    path: {{ .Values.github.chartPath }}
    helm:
      valueFiles:
        - values.yaml
  
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.application.namespace }}
  
  syncPolicy:
    {{- if .Values.sync.automated }}
    automated:
      prune: {{ .Values.sync.prune }}
      selfHeal: {{ .Values.sync.selfHeal }}
      allowEmpty: false
    {{- end }}
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
